version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: your_dbname
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
